/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "log_rpc.h"


void
log_rpc_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	cadena log_operation_1_usuario;
	cadena log_operation_1_operacion;
	cadena log_operation_1_fichero;

#ifndef	DEBUG
	clnt = clnt_create (host, LOG_RPC, LOG_RPC_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = log_operation_1(log_operation_1_usuario, log_operation_1_operacion, log_operation_1_fichero, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	log_rpc_1 (host);
exit (0);
}
