/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "log_rpc.h"

bool_t
xdr_cadena (XDR *xdrs, cadena *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_log_operation_1_argument (XDR *xdrs, log_operation_1_argument *objp)
{
	 if (!xdr_cadena (xdrs, &objp->usuario))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->operacion))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->fichero))
		 return FALSE;
	return TRUE;
}
