/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_RPC_H_RPCGEN
#define _LOG_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


typedef char *cadena;

struct log_operation_1_argument {
	cadena usuario;
	cadena operacion;
	cadena fichero;
};
typedef struct log_operation_1_argument log_operation_1_argument;

#define LOG_RPC 0x0522281
#define LOG_RPC_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_OPERATION 1
extern  enum clnt_stat log_operation_1(cadena , cadena , cadena , int *, CLIENT *);
extern  bool_t log_operation_1_svc(cadena , cadena , cadena , int *, struct svc_req *);
extern int log_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_OPERATION 1
extern  enum clnt_stat log_operation_1();
extern  bool_t log_operation_1_svc();
extern int log_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_cadena (XDR *, cadena*);
extern  bool_t xdr_log_operation_1_argument (XDR *, log_operation_1_argument*);

#else /* K&R C */
extern bool_t xdr_cadena ();
extern bool_t xdr_log_operation_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_RPC_H_RPCGEN */
