/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "log_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
log_operation_1(cadena usuario, cadena operacion, cadena fichero, int *clnt_res,  CLIENT *clnt)
{
	log_operation_1_argument arg;
	arg.usuario = usuario;
	arg.operacion = operacion;
	arg.fichero = fichero;
	return (clnt_call (clnt, LOG_OPERATION, (xdrproc_t) xdr_log_operation_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
