/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "log_rpc.h"
#include <stdio.h>
#include <string.h>

bool_t
log_operation_1_svc(cadena usuario, cadena operacion, cadena fichero, int *result,  struct svc_req *rqstp)
{
	// Silenciamos el warning de parámetro no usado para que no salten warnings
    (void)rqstp;

    // validamos que no haya nulos en los datos pasados
    if (usuario == NULL || operacion == NULL) {
        *result = -1;
        return TRUE;
    }

    // imprimimos en la terminal de rpc segun sea la funcion
    if (strcmp(operacion, "SENDATTACH") == 0 && fichero != NULL && fichero[0] != '\0') {
        printf("%s\t%s\t%s\n", usuario, operacion, fichero);
    } else {
        printf("%s\t%s\n", usuario, operacion);
    }

    //con esto aparece directamente en la terminal
    fflush(stdout);

    *result = 0;
    return TRUE;
}

int
log_rpc_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	(void)transp;
    xdr_free(xdr_result, result);
    return 1;
}
